nfd:
  enabled: false

labeller:
  enabled: false

dp:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.31.0.2"
  resources: {}

lbl:
  image:
    repository: docker.io/rocm/k8s-device-plugin
    tag: "labeller-1.31.0.2"
  resources: {}

imagePullSecrets: []

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

tolerations:
  - key: amd.com/gpu
    operator: Exists
    effect: NoSchedule
  - key: training-operator-job-gpu
    operator: Exists
    effect: NoSchedule

node_selector_enabled: false
node_selector:
  kubernetes.io/arch: amd64
