# Config values for ray-cluster helm deployment.
# For details see https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster

image:
  repository: rayproject/ray-ml
  tag: 2.30.0
  pullPolicy: IfNotPresent
head:
  enableInTreeAutoscaling: true

  containerEnv:
    - name: RAY_LOG_TO_STDERR
      value: "1"
    - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
      value: "python"

  resources:
    limits:
      cpu: "1"
      # To avoid out-of-memory issues, never allocate less than 2G memory for the Ray head.
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"
  tolerations:
    - key: "ray-cluster-head"
      effect: "NoSchedule"

worker:
  containerEnv:
    - name: RAY_LOG_TO_STDERR
      value: "1"
    - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
      value: "python"
  replicas: 0
  minReplicas: 0
  maxReplicas: 30
  resources:
    limits:
      cpu: "2"
      memory: "12G"
    requests:
      cpu: "2"
      memory: "12G"
  nodeSelector:
    NodeGroupType: "ray-cluster-worker"
  tolerations:
    - key: "ray-cluster-worker"
      effect: "NoSchedule"
